### ISSUE TITLE
Use skopeo to pull image digest

### ISSUE THREAD

**Issue by lioramilbaum** [michaelperel/docker-lock#10]
We are using an internal registry. The only way to access the digest is via skopeo

**Comment by lioramilbaum** [comment]
Hey @michaelperel. I am from Red Hat. I find your project very interesting. Would like to collaborate with you on this.

**Comment by michaelperel** [comment]
Hi @lioramilbaum, I would love to collaborate and ensure docker-lock can be useful for you. Out of the box, docker-lock supports a variety of container registries such as Azure Container Registry, DockerHub, and a few others. In these cases, docker-lock gets digests by querying the registries via the [Registry v2 API](https://docs.docker.com/registry/spec/api/), and it is extensible to any registry as long as a developer [implements a very simple interface](https://github.com/michaelperel/docker-lock/blob/master/registry/wrapper.go).

**In your specific case, how could I be the most helpful?**

I was thinking that perhaps I could setup a private Docker Registry and ensure docker-lock could access the digests? If so, would you have any specific requirements?

I also welcome any contributions and would be happy to help craft an issue with acceptance criteria, if you would like to work on it. I would also be available to pair program.

Thanks for your interest!

**Comment by lioramilbaum** [comment]
@michaelperel Thanks for getting back to me. Can we jump to a short video call? I am available in gmeet and zoom. My email is: lmilbaum@redhat.com.

**Comment by michaelperel** [comment]
@lioramilbaum Absolutely! Just sent you an email :)

**Comment by michaelperel** [comment]
@lioramilbaum Thank you for helping add support for internal registries. This is officially supported in the most recent release, v0.4.0.

In the upcoming week or so, I will add tutorials for the various container registries and reference them in the README.

**Comment by michaelperel** [comment]
The tutorial for internal registries can be found [here](https://github.com/michaelperel/docker-lock/blob/master/docs/tutorials/internal-registry.md). Thanks!
