### ISSUE TITLE
Track manifest list digest instead of image digest

### ISSUE THREAD

**Issue by lioramilbaum** [michaelperel/docker-lock#11]
Manifest list digest is useful when supporting multi-arch builds.
Additional information: https://docs.docker.com/registry/spec/manifest-v2-2/

**Comment by lioramilbaum** [comment]
The generate should populate the manifest list digest. Not sure if the manifest list itself should be populated. It might be an extra attribute for future usage.

**Comment by lioramilbaum** [comment]
I was hoping to find a way to reference a parent image with a manifests list digest. Didn't find anything valuable. That mean that during build time the parent image reference should be populated with the image digest for the arch we are building.

**Comment by lioramilbaum** [comment]
Another thought - instead of rewriting the Dockerfile, letting the `docker build` command to pick up the parent image reference from the lockfile as apposed to the reference in the FROM instruction (Dockerfile).

**Comment by michaelperel** [comment]
We were able to get a digest that works for all operating systems and architectures by specifying the header: `application/vnd.docker.distribution.manifest.list.v2+json`. For those curious, you can read more about this manifest list, aka "fat manifest", [here](https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md).

This means that `docker lock generate` will produce fat manifest digests wherever possible, and `docker lock rewrite`'s behavior can remain unchanged.

This behavior is available in version `v0.5.1`.

Thanks again for the feature request :)

**Comment by lioramilbaum** [comment]
Verified
